version: '3.9'

networks: 
    tig-net:
        driver: bridge

volumes:
    tig-data:

services:
    influxdb:
        image: influxdb:2.6.1
        container_name: influxdb
        ports:
            - 8086:8086
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: "wireless"
            INFLUXDB_ADMIN_USER: ""
            INFLUXDB_ADMIN_PASSWORD: "micropython"
        networks: 
            - tig-net
        volumes:
            - tig-data:/var/lib/influxdb

    grafana:
        image: grafana/grafana-oss:9.4.3
        container_name: grafana
        ports: 
            - 3000:3000
        environment:
            GF_SECURITY_ADMIN_USER: ryan
            GF_SECURITY_ADMIN_PASSWORD: password
        networks: 
            - tig-net
        volumes:
            - tig-data:/var/lib/grafana     

    rrdrest:
        image: michaelwadman/rrdrest:latest
        container_name: rrdrest
        ports: 
            - 9000:9000
        volumes:
            - "/opt/librenms:/opt/librenms"
        environment:
            - TZ=America/Denver

    # telegraf:
    #     image: telegraf:1.25.0
    #     depends_on: 
    #         - "influxdb"
    #     environment:
    #         HOST_NAME: "telegraf"
    #         INFLUXDB_HOST: "influxdb"
    #         INFLUXDB_PORT: "8086"
    #         DATABASE: "iot"
    #     volumes:
    #         - ./telegraf.conf:/etc/telegraf/telegraf.conf
    #     tty: true
    #     networks: 
    #         - tig-net
    #     privileged: true
